<?php

namespace EPGImporter\Entity\Repository;

/**
 * ServiceLivetvProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLivetvProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
