<?php

namespace EPGImporter\Entity\Repository;

/**
 * ServiceLivetvScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLivetvScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
