<?php

namespace EPGImporter\Entity\Repository;

/**
 * ServiceLivetvShowTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLivetvShowTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
