<?php

namespace EPGImporter\Entity\Repository;

use Doctrine\ORM\Query;

/**
 * ServiceLivetvChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLivetvChannelRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function getAllChannels()
    {
        return $this->_em->createQuery('SELECT c FROM EPGImporter\Entity\ServiceLivetvChannel c')
            ->getResult(Query::HYDRATE_OBJECT);
    }
}
